### ISSUE TITLE
Version, two or three digits to CRAN?

### ISSUE THREAD

**Issue by sebpardo** [ropensci/rebird#35]
Currently rebird releases only two digits to CRAN, and uses the third one for the development versions. I've seen that most other packages (and what Hadley recommends in his book) is to release three digits to CRAN and use the fourth one for devel. 

@sckott does ROpenSci have a standard for this?

**Comment by sckott** [comment]
we do use 4 places, and iterate through the 4th while iterating through changes on github, but the 3rd place, or the patch version, can be iterated too on github if change is big enough. 

The goal is to shoot for releasing minor versions to CRAN (.e.g, `v0.1.0`, `v0.2.0`), but sometimes you need to push up some critical changes, and they don't deserve a full minor version bump, so sometimes we push up a minor version change (e.g., `v0.1.4`). If I push minor versions to CRAN, I try to only push even numbers (e.g., `v0.1.4` instead of `v0.1.3`). 

Right, the 4th comes off when you push to CRAN, but after they accept it and what you pushed to CRAN is tagged here with that version number, then I add the 4th back so it's pretty obvious when someone is using a version from github given the 4 places

**Comment by sebpardo** [comment]
Soour next release should be `v0.3.0` instead of `v0.3`?

**Comment by sckott** [comment]
yep

**Comment by sebpardo** [comment]
Sweet, thank you for the clarification.
